In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt 

dataset = pd.read_csv('C:/Users/SHIVANGI GUPTA/Documents/College PDFs/Sem-V/Elective 2- Data Analytics/details.csv', header=None)
dataset.head(2)

0   1   2         3         4          5         6         7         8   \
0   1   1   1  0.741878  0.033103  17.240803  5.452007 -0.011167  0.025178   
1   1   1   1  0.730280  0.029398  17.609236  5.065307 -0.011026  0.024742   

         9        10        11        12        13        14        15  \
0  0.016555  0.01226  0.004946  0.009310  0.001166  0.001056  0.000304   
1  0.019960  0.01631  0.005169  0.007958  0.001348  0.001372  0.000193   

         16  
0  0.000295  
1  0.000144

In [2]:
dataset.describe(include='all')

0            1            2            3            4   \
count  1440.000000  1440.000000  1440.000000  1440.000000  1440.000000   
mean      4.733333     1.466667     0.500000     0.651485     0.042916   
std       2.175356     0.499061     0.500174     0.068892     0.016321   
min       1.000000     1.000000     0.000000     0.451768     0.010507   
25%       3.000000     1.000000     0.000000     0.608887     0.031593   
50%       5.000000     1.000000     0.500000     0.664519     0.040745   
75%       7.000000     2.000000     1.000000     0.704543     0.050701   
max       8.000000     2.000000     1.000000     0.785410     0.130125   

                5            6            7            8            9   \
count  1440.000000  1440.000000  1440.000000  1440.000000  1440.000000   
mean     18.648201     4.623741     0.000713     0.016919     0.282462   
std       0.966975     0.516899     0.007195     0.007731     0.846848   
min      15.527443     3.046966    -0.021561     0.002932     0.000533   
25%      17.972610     4.293062    -0.004221     0.011469     0.020353   
50%      18.619720     4.679566     0.000753     0.015737     0.064134   
75%      19.238081     4.990831     0.005195     0.021057     0.211921   
max      21.914929     5.981041     0.027705     0.055035    16.809935   

                10           11           12           13           14  \
count  1440.000000  1440.000000  1440.000000  1440.000000  1440.000000   
mean      0.418446     0.542544     0.652432     0.205126     0.261808   
std       1.595897     1.759491     2.515182     0.792666     1.222381   
min       0.000328     0.000019     0.000024     0.000004     0.000003   
25%       0.021871     0.009036     0.009802     0.001616     0.001639   
50%       0.070562     0.045330     0.045931     0.009216     0.009043   
75%       0.287687     0.221398     0.228964     0.055196     0.055404   
max      37.530891    25.389278    40.882316    14.219903    20.427559   

                15           16  
count  1440.000000  1440.000000  
mean      0.038610     0.036167  
std       0.137835     0.146518  
min       0.000002     0.000002  
25%       0.000252     0.000186  
50%       0.001617     0.001321  
75%       0.011045     0.008517  
max       1.831944     2.072301

In [7]:
# creating input features and target variables
X= dataset.iloc[:,3:17]
y= dataset.iloc[:,0]

In [8]:
X.head(2)

3         4          5         6         7         8         9   \
0  0.741878  0.033103  17.240803  5.452007 -0.011167  0.025178  0.016555   
1  0.730280  0.029398  17.609236  5.065307 -0.011026  0.024742  0.019960   

        10        11        12        13        14        15        16  
0  0.01226  0.004946  0.009310  0.001166  0.001056  0.000304  0.000295  
1  0.01631  0.005169  0.007958  0.001348  0.001372  0.000193  0.000144

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)
X

array([[ 1.31254565, -0.60150695, -1.45596933, ..., -0.21338849,
        -0.27800729, -0.24491821],
       [ 1.144144  , -0.8285502 , -1.07482106, ..., -0.21312999,
        -0.27881247, -0.24594868],
       [ 1.35122488, -0.04803802, -1.31853595, ..., -0.21047183,
        -0.27882972, -0.24590668],
       ...,
       [-1.12550855,  0.15616116, -0.41793984, ..., -0.16667768,
        -0.19226861, -0.18148795],
       [-0.72238082, -0.95896952, -0.22015519, ..., -0.14462369,
        -0.20029241, -0.20758588],
       [-0.28661147,  0.14645661, -0.37628502, ..., -0.0747627 ,
        -0.25255224, -0.22320433]])

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [11]:
from keras import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [12]:
classifier = Sequential()
#First Hidden Layer
classifier.add(Dense(7, activation='relu', kernel_initializer='random_normal', input_dim=14))
#Second  Hidden Layer
classifier.add(Dense(7, activation='relu', kernel_initializer='random_normal'))
#Output Layer
classifier.add(Dense(1, activation='sigmoid', kernel_initializer='random_normal'))

In [13]:
#Compiling the neural network
classifier.compile(optimizer ='adam',loss='binary_crossentropy', metrics =['accuracy'])

In [17]:
#Fitting the data to the training dataset
classifier.fit(X_train,y_train, batch_size=10, epochs=100)
scores = classifier.evaluate(X_test, y_test)
print("\n%s: %.2f%%" % (classifier.metrics_names[1], scores[1]*100))

Epoch 1/100
1008/1008 [==============================] - 0s 99us/step - loss: -303480.7792 - accuracy: 0.0635
Epoch 2/100
1008/1008 [==============================] - 0s 93us/step - loss: -310982.0085 - accuracy: 0.0635
Epoch 3/100
1008/1008 [==============================] - 0s 94us/step - loss: -318590.8501 - accuracy: 0.0635
Epoch 4/100
1008/1008 [==============================] - 0s 89us/step - loss: -326335.4713 - accuracy: 0.0635
Epoch 5/100
1008/1008 [==============================] - 0s 93us/step - loss: -334172.7930 - accuracy: 0.0635
Epoch 6/100
1008/1008 [==============================] - 0s 92us/step - loss: -342136.7734 - accuracy: 0.0635
Epoch 7/100
1008/1008 [==============================] - 0s 95us/step - loss: -350230.4909 - accuracy: 0.0635
Epoch 8/100
1008/1008 [==============================] - 0s 95us/step - loss: -358408.3796 - accuracy: 0.0635
Epoch 9/100
1008/1008 [==============================] - 0s 94us/step - loss: -366724.0308 - accuracy: 0.0635
Epoch 10/1

1008/1008 [==============================] - 0s 107us/step - loss: -1191123.0518 - accuracy: 0.0635
Epoch 75/100
1008/1008 [==============================] - 0s 111us/step - loss: -1208679.7228 - accuracy: 0.0635
Epoch 76/100
1008/1008 [==============================] - 0s 97us/step - loss: -1226392.0865 - accuracy: 0.0635
Epoch 77/100
1008/1008 [==============================] - 0s 102us/step - loss: -1244254.6683 - accuracy: 0.0635
Epoch 78/100
1008/1008 [==============================] - 0s 99us/step - loss: -1262345.0883 - accuracy: 0.0635
Epoch 79/100
1008/1008 [==============================] - 0s 102us/step - loss: -1280571.1517 - accuracy: 0.0635
Epoch 80/100
1008/1008 [==============================] - 0s 98us/step - loss: -1299018.8421 - accuracy: 0.0635
Epoch 81/100
1008/1008 [==============================] - 0s 102us/step - loss: -1317564.0098 - accuracy: 0.0635
Epoch 82/100
1008/1008 [==============================] - 0s 103us/step - loss: -1336355.0161 - accuracy: 0.0635

In [15]:
y_pred=classifier.predict(X_test)
y_pred =(y_pred>0.5)

In [18]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[32  0  0  0  0  0  0  0]
 [52  0  0  0  0  0  0  0]
 [55  0  0  0  0  0  0  0]
 [56  0  0  0  0  0  0  0]
 [59  0  0  0  0  0  0  0]
 [59  0  0  0  0  0  0  0]
 [63  0  0  0  0  0  0  0]
 [56  0  0  0  0  0  0  0]]
