In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report,confusion_matrix
from sklearn import metrics
from sklearn.model_selection import cross_val_score
from sklearn import preprocessing
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import BaggingClassifier

In [2]:
df = pd.read_csv('C:/Users/grees/OneDrive/Documents/Computer Science/Data Analytics/Audio-Emotion-Recognition/extractedData/details.csv')

In [3]:
X = df[list(df.columns)[3:]] #to get the relevant columnns (tonnetz, MFCC, chroma etc.)
X = preprocessing.normalize(X) #to normalize the data
y = df['emotion']
X = np.asarray(X)
y = np.asarray(y)
#X.shape, y.shape

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)
#to split data into training and testing => 75:25 ratio

In [5]:
#decision tree classifier
dtree = DecisionTreeClassifier()
dtree.fit(X_train, y_train)
predictions = dtree.predict(X_test)
accuracy=metrics.accuracy_score(y_test, predictions)
print(classification_report(y_test,predictions))
print("Confusion matrix for decision trees:")
print(confusion_matrix(y_test,predictions))
scores1 = cross_val_score(dtree, X, y, cv=10)
print("Accuracy: %0.2f (+/- %0.2f)" % (scores1.mean(), scores1.std()))

              precision    recall  f1-score   support

         1.0       0.25      0.18      0.21        22
         2.0       0.58      0.50      0.54        56
         3.0       0.27      0.33      0.30        42
         4.0       0.35      0.38      0.37        50
         5.0       0.38      0.54      0.44        50
         6.0       0.38      0.41      0.40        39
         7.0       0.35      0.26      0.30        46
         8.0       0.29      0.22      0.25        55

   micro avg       0.37      0.37      0.37       360
   macro avg       0.36      0.35      0.35       360
weighted avg       0.37      0.37      0.36       360

Confusion matrix for decision trees:
[[ 4  6  1  4  1  3  2  1]
 [ 6 28  3 15  2  0  1  1]
 [ 0  1 14  3 12  2  3  7]
 [ 2  9  5 19  5  3  3  4]
 [ 1  0  6  2 27  6  4  4]
 [ 0  1  8  3  4 16  1  6]
 [ 0  1  6  3 10  7 12  7]
 [ 3  2  9  5 11  5  8 12]]
Accuracy: 0.28 (+/- 0.04)


In [6]:
#random forest classifier
rfor = RandomForestClassifier(n_estimators=10, random_state = 45)
rfor = rfor.fit(X_train, y_train)
predictions2 = rfor.predict(X_test)
print(classification_report(y_test,predictions2))
accuracy=metrics.accuracy_score(y_test, predictions2)
print("Confusion matrix for random forest:")
print(confusion_matrix(y_test,predictions2))
scores2 = cross_val_score(rfor, X, y, cv=5)      
print("Accuracy: %0.2f (+/- %0.2f)" % (scores2.mean(), scores2.std()))

              precision    recall  f1-score   support

         1.0       0.27      0.32      0.29        22
         2.0       0.53      0.73      0.62        56
         3.0       0.27      0.43      0.33        42
         4.0       0.31      0.26      0.28        50
         5.0       0.58      0.50      0.54        50
         6.0       0.57      0.51      0.54        39
         7.0       0.29      0.22      0.25        46
         8.0       0.50      0.33      0.40        55

   micro avg       0.42      0.42      0.42       360
   macro avg       0.42      0.41      0.41       360
weighted avg       0.43      0.42      0.42       360

Confusion matrix for random forest:
[[ 7  9  2  2  0  0  2  0]
 [ 3 41  0  9  0  0  3  0]
 [ 2  2 18  2  4  8  3  3]
 [ 4 17  6 13  2  1  3  4]
 [ 1  0 10  2 25  1  6  5]
 [ 2  0  7  3  4 20  1  2]
 [ 4  4 13  6  3  2 10  4]
 [ 3  4 11  5  5  3  6 18]]
Accuracy: 0.31 (+/- 0.02)


In [7]:
#Extra trees classifier
clf = ExtraTreesClassifier(n_estimators=10, max_depth=None,min_samples_split=2, random_state=45)
scores3 = cross_val_score(clf, X, y, cv=10)
print("\nAccuracy for Extra Trees: %0.2f (+/- %0.2f)" % (scores3.mean(), scores3.std()))


Accuracy for Extra Trees: 0.31 (+/- 0.02)


In [8]:
#AdaBoost Classifier
clf = AdaBoostClassifier(n_estimators=20)
scores4 = cross_val_score(clf, X, y, cv=10)
print("\nAccuracy for AdaBoost: %0.2f (+/- %0.2f)" % (scores4.mean(), scores4.std()))


Accuracy for AdaBoost: 0.27 (+/- 0.03)


In [9]:
#Gradient boosting classifier
gb_clf = GradientBoostingClassifier(n_estimators=20, learning_rate=0.05, max_features=2, max_depth=2, random_state=0)
gb = gb_clf.fit(X_train, y_train)
predictions3 = gb.predict(X_test)
print(classification_report(y_test,predictions3))
accuracy=metrics.accuracy_score(y_test, predictions3)
print("Confusion matrix for gradient boosting:")
print(confusion_matrix(y_test,predictions3))
scores5 = cross_val_score(gb_clf, X, y, cv=10)
print("Accuracy: %0.2f (+/- %0.2f)" % (scores5.mean(), scores5.std()))

              precision    recall  f1-score   support

         1.0       0.00      0.00      0.00        22
         2.0       0.47      0.82      0.60        56
         3.0       0.26      0.36      0.30        42
         4.0       0.50      0.28      0.36        50
         5.0       0.62      0.48      0.54        50
         6.0       0.46      0.33      0.39        39
         7.0       0.36      0.46      0.40        46
         8.0       0.37      0.29      0.33        55

   micro avg       0.41      0.41      0.41       360
   macro avg       0.38      0.38      0.36       360
weighted avg       0.41      0.41      0.40       360

Confusion matrix for gradient boosting:
[[ 0 18  1  0  0  0  2  1]
 [ 3 46  2  3  0  0  2  0]
 [ 1  2 15  2  7  2  8  5]
 [ 0 20  3 14  0  1  6  6]
 [ 0  1  9  0 24  3  5  8]
 [ 0  2  7  4  7 13  4  2]
 [ 1  5  8  3  1  2 21  5]
 [ 4  4 12  2  0  7 10 16]]
Accuracy: 0.32 (+/- 0.03)


In [10]:

#Bagging using Decision Trees
bagging = BaggingClassifier(DecisionTreeClassifier(), max_samples=0.3, max_features=0.7) #more dependent on features than samples
scores6 = cross_val_score(bagging, X, y, cv=10)
print("\nAccuracy after bagging with Decision Trees: %0.2f (+/- %0.2f)" % (scores6.mean(), scores6.std()))


Accuracy after bagging with Decision Trees: 0.29 (+/- 0.03)
