In [16]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report,confusion_matrix
from sklearn import metrics
from sklearn.model_selection import cross_val_score
from sklearn import preprocessing
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import BaggingClassifier
from xgboost import XGBClassifier
from sklearn import svm
from sklearn.neural_network import MLPClassifier
import pickle

In [17]:
df = pd.read_csv('../../extractedData/details.csv')

In [18]:
X = df[list(df.columns)[3:]] #to get the relevant columnns (tonnetz, MFCC, chroma etc.)
#X = preprocessing.normalize(X) #to normalize the data
y = df['emotion']
X = np.asarray(X)
y = np.asarray(y)
#X.shape, y.shape

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)
#to split data into training and testing => 75:25 ratio

In [20]:
#decision tree classifier
dtree = DecisionTreeClassifier()
dtree.fit(X_train, y_train)
predictions = dtree.predict(X_test)
accuracy=metrics.accuracy_score(y_test, predictions)
print(classification_report(y_test,predictions))
print("Confusion matrix for decision trees:")
print(confusion_matrix(y_test,predictions))
scores1 = cross_val_score(dtree, X, y, cv=10)
print("Accuracy: %0.2f (+/- %0.2f)" % (scores1.mean(), scores1.std()))

              precision    recall  f1-score   support

         1.0       0.19      0.18      0.19        22
         2.0       0.48      0.48      0.48        56
         3.0       0.26      0.29      0.27        42
         4.0       0.26      0.32      0.29        50
         5.0       0.57      0.62      0.60        50
         6.0       0.33      0.36      0.34        39
         7.0       0.13      0.11      0.12        46
         8.0       0.55      0.40      0.46        55

   micro avg       0.36      0.36      0.36       360
   macro avg       0.35      0.34      0.34       360
weighted avg       0.37      0.36      0.36       360

Confusion matrix for decision trees:
[[ 4  8  0  5  1  1  3  0]
 [ 6 27  1 15  0  2  5  0]
 [ 4  1 12  3  5  9  5  3]
 [ 2 11  6 16  0  7  6  2]
 [ 1  1  7  2 31  4  2  2]
 [ 1  3  8  4  4 14  5  0]
 [ 3  2  7 11  4  3  5 11]
 [ 0  3  6  5  9  3  7 22]]
Accuracy: 0.28 (+/- 0.05)


In [21]:
#random forest classifier
rfor = RandomForestClassifier(n_estimators=10, random_state = 45)
rfor = rfor.fit(X_train, y_train)
predictions2 = rfor.predict(X_test)
print(classification_report(y_test,predictions2))
accuracy=metrics.accuracy_score(y_test, predictions2)
print("Confusion matrix for random forest:")
print(confusion_matrix(y_test,predictions2))
scores2 = cross_val_score(rfor, X, y, cv=5)      
print("Accuracy: %0.2f (+/- %0.2f)" % (scores2.mean(), scores2.std()))

              precision    recall  f1-score   support

         1.0       0.29      0.27      0.28        22
         2.0       0.50      0.66      0.57        56
         3.0       0.26      0.40      0.32        42
         4.0       0.28      0.22      0.25        50
         5.0       0.54      0.58      0.56        50
         6.0       0.43      0.38      0.41        39
         7.0       0.29      0.20      0.23        46
         8.0       0.51      0.38      0.44        55

   micro avg       0.40      0.40      0.40       360
   macro avg       0.39      0.39      0.38       360
weighted avg       0.40      0.40      0.40       360

Confusion matrix for random forest:
[[ 6  9  1  3  0  0  2  1]
 [ 5 37  0 10  0  0  2  2]
 [ 0  3 17  2  8  5  4  3]
 [ 4 15  6 11  0  7  4  3]
 [ 0  1  9  1 29  1  3  6]
 [ 2  1 10  6  3 15  2  0]
 [ 2  5 12  3  6  4  9  5]
 [ 2  3 10  3  8  3  5 21]]
Accuracy: 0.32 (+/- 0.01)


In [22]:
#Extra trees classifier
clf = ExtraTreesClassifier(n_estimators=10, max_depth=None,min_samples_split=2, random_state=45)
clf.fit(X_train, y_train)
predictions6 = clf.predict(X_test)
accuracy=metrics.accuracy_score(y_test, predictions6)
print(classification_report(y_test,predictions6))
print("Confusion matrix for Extra Trees Classifier:")
print(confusion_matrix(y_test,predictions2))
scores3 = cross_val_score(clf, X, y, cv=10)
print("\nAccuracy for Extra Trees: %0.2f (+/- %0.2f)" % (scores3.mean(), scores3.std()))

              precision    recall  f1-score   support

         1.0       0.26      0.27      0.27        22
         2.0       0.44      0.59      0.50        56
         3.0       0.25      0.36      0.30        42
         4.0       0.38      0.34      0.36        50
         5.0       0.49      0.52      0.50        50
         6.0       0.53      0.59      0.56        39
         7.0       0.19      0.13      0.15        46
         8.0       0.60      0.33      0.42        55

   micro avg       0.40      0.40      0.40       360
   macro avg       0.39      0.39      0.38       360
weighted avg       0.41      0.40      0.39       360

Confusion matrix for Extra Trees Classifier:
[[ 6  9  1  3  0  0  2  1]
 [ 5 37  0 10  0  0  2  2]
 [ 0  3 17  2  8  5  4  3]
 [ 4 15  6 11  0  7  4  3]
 [ 0  1  9  1 29  1  3  6]
 [ 2  1 10  6  3 15  2  0]
 [ 2  5 12  3  6  4  9  5]
 [ 2  3 10  3  8  3  5 21]]

Accuracy for Extra Trees: 0.33 (+/- 0.03)


In [23]:
#AdaBoost Classifier
clf = AdaBoostClassifier(n_estimators=20)
clf.fit(X_train, y_train)
predictions7 = clf.predict(X_test)
accuracy=metrics.accuracy_score(y_test, predictions7)
print(classification_report(y_test,predictions7))
print("Confusion matrix for AdaBoost Classifier:")
print(confusion_matrix(y_test,predictions2))
scores4 = cross_val_score(clf, X, y, cv=10)
print("\nAccuracy for AdaBoost: %0.2f (+/- %0.2f)" % (scores4.mean(), scores4.std()))

              precision    recall  f1-score   support

         1.0       0.08      0.09      0.09        22
         2.0       0.40      0.71      0.52        56
         3.0       0.23      0.07      0.11        42
         4.0       0.33      0.08      0.13        50
         5.0       0.32      0.78      0.45        50
         6.0       0.24      0.10      0.14        39
         7.0       0.24      0.24      0.24        46
         8.0       0.26      0.13      0.17        55

   micro avg       0.31      0.31      0.31       360
   macro avg       0.26      0.28      0.23       360
weighted avg       0.28      0.31      0.25       360

Confusion matrix for AdaBoost Classifier:
[[ 6  9  1  3  0  0  2  1]
 [ 5 37  0 10  0  0  2  2]
 [ 0  3 17  2  8  5  4  3]
 [ 4 15  6 11  0  7  4  3]
 [ 0  1  9  1 29  1  3  6]
 [ 2  1 10  6  3 15  2  0]
 [ 2  5 12  3  6  4  9  5]
 [ 2  3 10  3  8  3  5 21]]

Accuracy for AdaBoost: 0.29 (+/- 0.03)


In [24]:
#Gradient boosting classifier
gb_clf = GradientBoostingClassifier(n_estimators=20, learning_rate=0.05, max_features=2, max_depth=2, random_state=0)
gb = gb_clf.fit(X_train, y_train)
predictions5 = gb.predict(X_test)
print(classification_report(y_test,predictions5))
accuracy=metrics.accuracy_score(y_test, predictions5)
print("Confusion matrix for gradient boosting:")
print(confusion_matrix(y_test,predictions5))
scores5 = cross_val_score(gb_clf, X, y, cv=10)
print("Accuracy: %0.2f (+/- %0.2f)" % (scores5.mean(), scores5.std()))

              precision    recall  f1-score   support

         1.0       0.00      0.00      0.00        22
         2.0       0.44      0.79      0.57        56
         3.0       0.27      0.38      0.31        42
         4.0       0.58      0.28      0.38        50
         5.0       0.61      0.54      0.57        50
         6.0       0.40      0.31      0.35        39
         7.0       0.26      0.30      0.28        46
         8.0       0.47      0.36      0.41        55

   micro avg       0.41      0.41      0.41       360
   macro avg       0.38      0.37      0.36       360
weighted avg       0.41      0.41      0.39       360

Confusion matrix for gradient boosting:
[[ 0 18  2  0  0  0  2  0]
 [ 2 44  2  5  0  1  2  0]
 [ 1  4 16  2  6  5  4  4]
 [ 1 16  8 14  0  2  6  3]
 [ 0  1  5  0 27  4  4  9]
 [ 1  3  8  1  8 12  4  2]
 [ 1  7 15  2  1  1 14  5]
 [ 1  6  4  0  2  5 17 20]]
Accuracy: 0.32 (+/- 0.03)


In [25]:
#Bagging using Decision Trees
bagging = BaggingClassifier(DecisionTreeClassifier(), max_samples=0.3, max_features=0.7) #more dependent on features than samples
bagging.fit(X_train, y_train)
predictions3 = bagging.predict(X_test)
accuracy=metrics.accuracy_score(y_test, predictions3)
print(classification_report(y_test,predictions3))
print("Confusion matrix for bagging with Decision Trees:")
print(confusion_matrix(y_test,predictions3))
scores6 = cross_val_score(bagging, X, y, cv=10)
print("\nAccuracy after bagging with Decision Trees: %0.2f (+/- %0.2f)" % (scores6.mean(), scores6.std()))

              precision    recall  f1-score   support

         1.0       0.19      0.23      0.21        22
         2.0       0.53      0.73      0.61        56
         3.0       0.24      0.33      0.28        42
         4.0       0.33      0.22      0.27        50
         5.0       0.51      0.52      0.51        50
         6.0       0.34      0.36      0.35        39
         7.0       0.29      0.26      0.28        46
         8.0       0.55      0.31      0.40        55

   micro avg       0.39      0.39      0.39       360
   macro avg       0.37      0.37      0.36       360
weighted avg       0.40      0.39      0.38       360

Confusion matrix for bagging with Decision Trees:
[[ 5 10  0  4  0  0  3  0]
 [ 5 41  3  1  0  0  5  1]
 [ 3  3 14  4  9  4  2  3]
 [ 5 14  9 11  2  5  4  0]
 [ 1  1  9  0 26  6  2  5]
 [ 1  3 10  4  5 14  1  1]
 [ 4  4  6  7  2  7 12  4]
 [ 2  2  8  2  7  5 12 17]]

Accuracy after bagging with Decision Trees: 0.30 (+/- 0.03)


In [26]:
xg = XGBClassifier()
xg.fit(X_train, y_train)
pickle.dump(xg, open("xgModelFinal.pickle.dat", "wb"))
predictions4 = xg.predict(X_test)
accuracy=metrics.accuracy_score(y_test, predictions4)
print(classification_report(y_test,predictions4))
print("Confusion matrix for decision trees:")
print(confusion_matrix(y_test,predictions4))
scores7 = cross_val_score(xg, X, y, cv=10)
print("Accuracy: %0.2f (+/- %0.2f)" % (scores7.mean(), scores7.std()))

              precision    recall  f1-score   support

         1.0       0.28      0.23      0.25        22
         2.0       0.56      0.71      0.63        56
         3.0       0.37      0.45      0.40        42
         4.0       0.43      0.30      0.35        50
         5.0       0.58      0.60      0.59        50
         6.0       0.49      0.46      0.47        39
         7.0       0.30      0.28      0.29        46
         8.0       0.49      0.45      0.47        55

   micro avg       0.46      0.46      0.46       360
   macro avg       0.44      0.44      0.43       360
weighted avg       0.45      0.46      0.45       360

Confusion matrix for decision trees:
[[ 5 10  1  3  0  0  3  0]
 [ 3 40  1  8  0  1  3  0]
 [ 2  3 19  0  9  2  4  3]
 [ 1 13  7 15  1  7  3  3]
 [ 1  1  4  0 30  3  1 10]
 [ 0  1  5  6  4 18  3  2]
 [ 4  4  8  2  4  3 13  8]
 [ 2  0  7  1  4  3 13 25]]
Accuracy: 0.35 (+/- 0.03)


In [12]:
clf = svm.SVC(kernel="linear")
clf.fit(X, y)
predictions8 = clf.predict(X_test)
print(classification_report(y_test,predictions8))
accuracy=metrics.accuracy_score(y_test, predictions8)
print("Confusion matrix for SVM:")
print(confusion_matrix(y_test,predictions8))
scores8 = cross_val_score(clf, X, y, cv=10)
print("Accuracy: %0.2f (+/- %0.2f)" % (scores8.mean(), scores8.std()))

C:\Users\AryaRajivChaloli\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


              precision    recall  f1-score   support

         1.0       0.00      0.00      0.00        22
         2.0       0.18      1.00      0.31        56
         3.0       0.00      0.00      0.00        42
         4.0       0.00      0.00      0.00        50
         5.0       0.86      0.48      0.62        50
         6.0       0.67      0.21      0.31        39
         7.0       0.00      0.00      0.00        46
         8.0       0.00      0.00      0.00        55

   micro avg       0.24      0.24      0.24       360
   macro avg       0.21      0.21      0.15       360
weighted avg       0.22      0.24      0.17       360

Confusion matrix for SVM:
[[ 0 22  0  0  0  0  0  0]
 [ 0 56  0  0  0  0  0  0]
 [ 0 37  0  0  0  1  4  0]
 [ 0 50  0  0  0  0  0  0]
 [ 0 21  0  0 24  2  2  1]
 [ 0 21  0  2  4  8  4  0]
 [ 0 46  0  0  0  0  0  0]
 [ 0 52  0  0  0  1  2  0]]
Accuracy: 0.19 (+/- 0.03)


In [13]:
clf = MLPClassifier(solver='lbfgs', alpha=1e-5,hidden_layer_sizes=(5, 2), random_state=1)
clf.fit(X, y)
predictions8 = clf.predict(X_test)
print(classification_report(y_test,predictions8))
accuracy=metrics.accuracy_score(y_test, predictions8)
print("Confusion matrix for ANN:")
print(confusion_matrix(y_test,predictions8))
scores8 = cross_val_score(clf, X, y, cv=10)
print("Accuracy: %0.2f (+/- %0.2f)" % (scores8.mean(), scores8.std()))

C:\Users\AryaRajivChaloli\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


              precision    recall  f1-score   support

         1.0       0.00      0.00      0.00        22
         2.0       0.33      0.91      0.49        56
         3.0       0.27      0.17      0.21        42
         4.0       0.12      0.18      0.15        50
         5.0       0.54      0.58      0.56        50
         6.0       0.21      0.08      0.11        39
         7.0       0.10      0.02      0.04        46
         8.0       0.28      0.15      0.19        55

   micro avg       0.30      0.30      0.30       360
   macro avg       0.23      0.26      0.22       360
weighted avg       0.25      0.30      0.24       360

Confusion matrix for ANN:
[[ 0 18  0  4  0  0  0  0]
 [ 0 51  0  4  0  0  0  1]
 [ 0 11  7  7  6  6  1  4]
 [ 0 34  1  9  0  0  2  4]
 [ 0  1  5  6 29  0  2  7]
 [ 0  8  5  3 16  3  1  3]
 [ 0 19  5 18  0  1  1  2]
 [ 0 11  3 23  3  4  3  8]]
Accuracy: 0.27 (+/- 0.03)
